# Generated by Django 5.2.17 on 2026-08-23 11:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('digest', models.CharField(max_length=71, validators=[django.core.validators.RegexValidator(message="Digest must be in the format 'sha256:' followed by 64 hex characters.", regex='^sha256:[0-9a-f]{64}$')])),
                ('size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='repositories.repository')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('repository', 'name'), name='unique_repository_tag_name')],
            },
        ),
    ]
